version: 2.1

orbs:
  cfn-lint: fatlama/cfn-lint@0.2.2

jobs:
  validate-template:
    executor: cfn-lint/default
    steps:
      - checkout
      - run:
         command: ls -la

workflows:
  main:
    jobs:
      - validate-template
